options:
  drone_sum:
    type: string
    default: a22db505822d6cccc6cfd5435eb4a18b4b3a60a58e0c32c6deaacf8c07626e5e
    description: "Sha256 sum of the drone payload from downloads.drone.io"
  github_enabled:
    type: boolean
    default: false
    description: "Enable GitHub integration"
  github_client:
    type: string
    default:
    description: "Github application client id"
  github_secret:
    type: string
    default:
    description: "Github application secret"
  gogs_enabled:
    type: boolean
    default: false
    description: "Enable Gogs integration"
  gogs_url:
    type: string
    default:
    description: "URL of GOGS server"
  gogs_secret:
    type: string
    default:
    description: "GOGS Application Secret Key"
