[server]
  port=":80"

[session]
  secret="{{appsecret}}"
  expires="72h"

{% if github_client != '' %}
[github]
  client = "{{ github_client }}"
  secret = "{{ github_secret }}"
{% endif %}

[worker] 
  nodes=[ 
     "unix:///var/run/docker.sock",
     "unix:///var/run/docker.sock",
     "unix:///var/run/docker.sock",
     "unix:///var/run/docker.sock"
  ]
