# The tasks here are left as examples and should be removed/replaced by the
# charm author. Some things to note:
# 1. All charm config values are available as template variables
#    e.g. repo -> {{repo}}, app-name -> {{app_name}} (note underscore)
# 2. Along with charm config values, the following variables are also
#    made available as template vars:
#    charm_dir
#    local_unit
#    unit_private_address
#    unit_public_address
# 3. Use tags to control when each task is executed. The tags list should
#    contain one or more hook names.

- hosts: all
    
  tasks:
    - name: install pwgen
      apt:  pkg="pwgen" state="installed"
      tags:
        - config-changed

    - name: Generate secret session token
      command: pwgen -c -s -1 60
      register: session_token
      tags:
        - config-changed

    - set_fact:
        appsecret: "{{session_token.stdout}}"
      notify: "render drone template"
      tags:
        - config-changed

    - name: Fetch Drone.
      get_url: url=http://downloads.drone.io/master/drone.deb dest=/tmp/drone.deb
      tags:
        - config-changed

    - name: Install Drone
      command: dpkg -i /tmp/drone.deb
      args:
         creates: /usr/local/bin/droned
      tags:
        - config-changed

    - name: render drone template
      template: src=../templates/drone.toml dest=/etc/drone/drone.toml
      tags:
        - config-changed

    - name: Restart Drone
      service: name=drone state=restarted
      tags:
        - start
        - config-changed

    - name: Stop Drone
      service: name=drone state=stopped
      tags:
        - stop
